#!/usr/bin/env fish

function main
    set total_tests 0
    set passed 0
    set failed 0

    while read stuff
        set match_n_tests (echo $stuff | string match -r -g '^1\.\.(\d+)')
        if not string-empty $match_n_tests
            set total_tests $match_n_tests
        else if equals $stuff 'ok'
            echo -n .
            set passed (math $passed + 1)
        else if equals $stuff 'not ok'
            echo -n F
            set failed (math $failed + 1)
        end
    end

    echo
    echo "$total_tests tests: $passed passed, $failed failures"

    if equals $total_tests $passed
        echo SUCCESS
    else
        echo FAILURE
        return 1
    end
end

main
