abbr -a -- - "cd -"
abbr -a -- 1 "npx @11ty/eleventy"
abbr -a -- 2 "git reset @^"
abbr -a -- 8 "curl localhost:8000"
abbr -a -- a "rg"
abbr -a -- ab "abbr-add"
abbr -a -- al "apt list --upgradable"
abbr -a -- alu "apt list --upgradable"
abbr -a -- au "sudo apt upgrade"
abbr -a -- bi "bundle install"
abbr -a -- br "bat README.md"
abbr -a -- c "cd"
abbr -a -- cc "clone-cd"
abbr -a -- cd- "cd -"
abbr -a -- cf "~/.config/fish/"
abbr -a -- chownme "sudo chown (whoami)"
abbr -a -- clj "clojure"
abbr -a -- cmd "command"
abbr -a -- cx "chmod +x"
abbr -a -- dl "~/Downloads/"
abbr -a -- ef "exec fish"
abbr -a -- ev "echo-variable"
abbr -a -- fe "funced"
abbr -a -- ffns "~/.config/fish/functions/"
abbr -a -- fl "funced-last"
abbr -a -- fn "function"
abbr -a -- fns "functions"
abbr -a -- fs "funcsave-last"
abbr -a -- ga "git-add"
abbr -a -- gau "git add -u"
abbr -a -- gb "git branch"
abbr -a -- gc "git-commit"
abbr -a -- gca "git commit --amend --no-edit"
abbr -a -- gd "git diff"
abbr -a -- gi "gem install"
abbr -a -- gl "git pull"
abbr -a -- glg "git log"
abbr -a -- gn "git new"
abbr -a -- gp "git push"
abbr -a -- gpf "git push --force"
abbr -a -- gq "git restore ."
abbr -a -- grc "git rebase --continue"
abbr -a -- grv "git remote -v"
abbr -a -- gs "git status"
abbr -a -- gsd "git stash drop"
abbr -a -- gw "git show"
abbr -a -- h "~/hack"
abbr -a -- hg "hugo"
abbr -a -- hu "hugo"
abbr -a -- i "ipython"
abbr -a -- k1 "kill %1"
abbr -a -- l "ls"
abbr -a -- lh "ls -lahtr"
abbr -a -- lrc "link-rc"
abbr -a -- lsblk "diskutil list"
abbr -a -- lt "lein test"
abbr -a -- m "git switch main"
abbr -a -- m "make"
abbr -a -- mdkir "mkdir"
abbr -a -- nb "newsboat"
abbr -a -- news "newsboat"
abbr -a -- nf "netlify"
abbr -a -- ng "npm install -g"
abbr -a -- ni "npm install"
abbr -a -- niy "npm init -y"
abbr -a -- nrb "npm run build"
abbr -a -- o "wslview"
abbr -a -- p "python"
abbr -a -- p3 "python3"
abbr -a -- pc "wl-copy"
abbr -a -- pei "pipenv install"
abbr -a -- perm "pipenv --rm"
abbr -a -- pes "pipenv shell"
abbr -a -- pi "pip install"
abbr -a -- pir "pip install -r requirements.txt"
abbr -a -- pm "python -m"
abbr -a -- pos "poetry shell"
abbr -a -- ptech "~/consulting/ptech-web"
abbr -a -- pu "pip uninstall -y"
abbr -a -- pvv "python -m venv venv"
abbr -a -- pws "~/.password-store/"
abbr -a -- re "git restore"
abbr -a -- rmd "rmdir"
abbr -a -- rmr "remove -r"
abbr -a -- rmrf "remove -rf"
abbr -a -- ro "cd (git root)"
abbr -a -- s "ssh"
abbr -a -- serve "python3 -m http.server"
abbr -a -- sov "source venv/bin/activate.fish"
abbr -a -- sp "source ~/.profile"
abbr -a -- sv "source venv/bin/activate.fish"
abbr -a -- sw "git switch"
abbr -a -- sy "symlink"
abbr -a -- sym "symlink"
abbr -a -- tm "tmux"
abbr -a -- uns "unsymlink"
abbr -a -- v "vim"
abbr -a -- vi "vim"
abbr -a -- vip "vim-plugin"
abbr -a -- vp "vim ~/.profile"
abbr -a -- vs "vagrant ssh"
abbr -a -- vu "vagrant up"
abbr -a -- vv "vim ~/.vimrc"
abbr -a -- w "weechat"
abbr -a -- wn "wikinews"
abbr -a -- x "exit"
abbr -a -- y "yarn"
abbr -a -- yb "yarn build"
abbr -a -- ys "yarn start"
