abbr -a -- a "rg"
abbr -a -- ab "abbr-add"
abbr -a -- cf "~/.config/fish/"
abbr -a -- ef "exec fish"
abbr -a -- fe "funced"
abbr -a -- fl "funced-last"
abbr -a -- fns "functions"
abbr -a -- ga "git-add"
abbr -a -- gc "git-commit"
abbr -a -- gd "git diff"
abbr -a -- gn "git new"
abbr -a -- gs "git status"
abbr -a -- p "python"
abbr -a -- v "vim"
abbr -a -- vv "vim ~/.vimrc"
